### ISSUE TITLE
Checksum mismatch 

### ISSUE THREAD

**Issue by princensecshop** [sk444/spring-boot-paytm-payment#1]
I followed these steps. Everytime i get a false from the validatechecksum method. The verify signature returns false. Could you check what is going wrong here?

**Comment by sk444** [comment]
Hi Prince,

Have you proceeded with the payment at the end?? I checked, for me, it's
working fine, let me know if you are still facing issue. You can also go
through the once official documentation from Paytm:
https://developer.paytm.com/docs/checksum/

**Comment by princensecshop** [comment]
I did the paytm page opens. Then i made a credit card payment. It redirects to my application. There when it goes to verify the checksum again it returns false. This is the problem.

**Comment by sk444** [comment]
Ohh, okay Prince, I tried with net banking, Now, I am checking with Credit
Card, will let you know soon.

**Comment by princensecshop** [comment]
were you able to do it with credit card?

**Comment by princensecshop** [comment]
Please Let me know if the credit payments are working as I am in final stages of my project work. If not we would seek paytm help.

**Comment by sk444** [comment]
Really sorry friend, I am not getting time due to very busy schedule, you
can please contact to Paytm regarding this.

**Comment by sk444** [comment]
Hi Princensecshop, I hope you have got the solution to fix the CheckSum Mismatch issue. If not I have fixed it and updated it on the git code. Please do check.

And I find many people are facing the checkSum Mismatch issue. So, it might be helpful for them.

**Comment by princensecshop** [comment]
Hey sk444,
The updated code also gives checksum mismatch problem. Have you verified all mode of payments.
